{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "kubewise-test.namespace" . }}
  labels:
    {{- include "kubewise-test.labels" . | nindent 4 }}
{{- end }}
